### ISSUE TITLE
width and height must be > 0

### ISSUE THREAD

**Issue by lgGuo** [nanchen2251/CompressHelper#10]
java.lang.IllegalArgumentException: width and height must be > 0

at android.graphics.Bitmap.createBitmap(Bitmap.java:867)

at android.graphics.Bitmap.createBitmap(Bitmap.java:846)

at android.graphics.Bitmap.createBitmap(Bitmap.java:813)

at com.nanchen.compresshelper.ImageUtil.getScaledBitmap(ImageUtil.java:129)

at com.nanchen.compresshelper.ImageUtil.compressImage(ImageUtil.java:175)

at com.nanchen.compresshelper.CompressHelper.compressToFile(CompressHelper.java:65)

at com.yctech.kindomgarden.qiniu.FileSyncService.synUpLoadFile(FileSyncService.java:342)

at com.yctech.kindomgarden.qiniu.FileSyncService.syncContent(FileSyncService.java:255)

at com.yctech.kindomgarden.qiniu.FileSyncService.onHandleIntent(FileSyncService.java:86)

at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:150)

at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by nanchen2251** [comment]
方便把你出错的那张图片发给我吗？我这里没法重现。

**Comment by nanchen2251** [comment]
帮忙再测试一下。不行把出问题的照片以及手机型号发我邮箱liushilin520@foxmail.com吧~

**Comment by lgGuo** [comment]
发你邮箱了
