### ISSUE TITLE
Hey  i used android 6  and o ram app and check button to Caused  Uufortunately CompressImage Has stop 

### ISSUE THREAD

**Issue by PongPloy2016** [nanchen2251/CompressHelper#19]
Hey  i used android 6  and o ram app and check button to Caused  Error

Image Photo [http://upload.i4th.in.th/th/download.php?id=591534801](url) 

File Logcat             

```
Caused by: java.lang.NullPointerException: file
                                                                               at android.net.Uri.fromFile(Uri.java:452)
                                                                               at com.nanchen.compresshelper.CompressHelper.compressToFile(CompressHelper.java:78)
                                                                               at com.nanchen.compressimage.MainActivity.compress(MainActivity.java:52)
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                               at android.view.View.performClick(View.java:5207) 
                                                                               at android.view.View$PerformClick.run(View.java:21168) 
                                                                               at android.os.Handler.handleCallback(Handler.java:746) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

**Comment by nanchen2251** [comment]
okay , I received your issues , I will solve the question as soon as possiable

**Comment by PongPloy2016** [comment]
@nanchen2251ok guy. Thank you to help
