### ISSUE TITLE
压缩会闪退

### ISSUE THREAD

**Issue by giantss** [nanchen2251/CompressHelper#23]
HM 2A  系统 : 4.4.4
操作步骤
1，启动app，点击照片。
2，有的照片可以，有的击有一些照片点击选择就会闪退（闪退的是大点的照片大概6M—8M）

**Comment by giantss** [comment]
`06-06 15:22:57.041 13097-13097/com.nanchen.compressimage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.nanchen.compressimage, PID: 13097
                                                                           java.lang.OutOfMemoryError
                                                                               at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
                                                                               at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:627)
                                                                               at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:603)
                                                                               at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
                                                                               at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:407)
                                                                               at com.nanchen.compressimage.MainActivity.onActivityResult(MainActivity.java:91)
                                                                               at android.app.Activity.dispatchActivityResult(Activity.java:5548)
                                                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:3372)
                                                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:3419)
                                                                               at android.app.ActivityThread.access$1300(ActivityThread.java:147)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1259)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5135)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
                                                                               at dalvik.system.NativeStart.main(Native Method)
`

**Comment by giantss** [comment]
￼




![1](https://cloud.githubusercontent.com/assets/13778798/26818676/30b9f06e-4ace-11e7-86b1-da4798869733.jpg)
￼

**Comment by nanchen2251** [comment]
你好，你的附件图片并不能看到。

**Comment by giantss** [comment]
![1](https://user-images.githubusercontent.com/13778798/27018534-e0a69b64-4f63-11e7-928e-d4cb18a31820.jpg)
@nanchen2251   额，我上传好了还点开看了，不知道现在怎么看不了了

**Comment by nanchen2251** [comment]
当前暂不支持大图压缩。
